/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const DashboardLazyImport = createFileRoute('/dashboard')()
const AuthLazyImport = createFileRoute('/auth')()
const IndexLazyImport = createFileRoute('/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const DashboardTeacherLazyImport = createFileRoute('/dashboard/teacher')()
const DashboardStudentLazyImport = createFileRoute('/dashboard/student')()
const DashboardCompanyLazyImport = createFileRoute('/dashboard/company')()
const DashboardAdminLazyImport = createFileRoute('/dashboard/admin')()
const AuthResetPasswordLazyImport = createFileRoute('/auth/reset-password')()
const AuthOneTimePasswordLazyImport = createFileRoute(
  '/auth/one-time-password',
)()
const AuthLoginLazyImport = createFileRoute('/auth/login')()
const AuthForgetPasswordLazyImport = createFileRoute('/auth/forget-password')()
const DashboardTeacherSuperviseProjectsLazyImport = createFileRoute(
  '/dashboard/teacher/supervise-projects',
)()
const DashboardTeacherSubmitProposalLazyImport = createFileRoute(
  '/dashboard/teacher/submit-proposal',
)()
const DashboardTeacherSelectSupervisionLazyImport = createFileRoute(
  '/dashboard/teacher/select-supervision',
)()
const DashboardTeacherPendingRevisionsLazyImport = createFileRoute(
  '/dashboard/teacher/pending-revisions',
)()
const DashboardTeacherManageDefenseScheduleLazyImport = createFileRoute(
  '/dashboard/teacher/manage-defense-schedule',
)()
const DashboardTeacherDashboardLazyImport = createFileRoute(
  '/dashboard/teacher/dashboard',
)()
const DashboardAdminUserManagmentLazyImport = createFileRoute(
  '/dashboard/admin/user-managment',
)()
const DashboardAdminSupervisionLazyImport = createFileRoute(
  '/dashboard/admin/supervision',
)()
const DashboardAdminProjectManagmentLazyImport = createFileRoute(
  '/dashboard/admin/project-managment',
)()
const DashboardAdminPfeProposalsLazyImport = createFileRoute(
  '/dashboard/admin/pfe-proposals',
)()
const DashboardAdminEmailTemplateLazyImport = createFileRoute(
  '/dashboard/admin/email-template',
)()
const DashboardAdminEmailScheduleLazyImport = createFileRoute(
  '/dashboard/admin/email-schedule',
)()
const DashboardAdminDefenseScheduleLazyImport = createFileRoute(
  '/dashboard/admin/defense-schedule',
)()
const DashboardAdminDashboardLazyImport = createFileRoute(
  '/dashboard/admin/dashboard',
)()
const DashboardAdminAddUserLazyImport = createFileRoute(
  '/dashboard/admin/add-user',
)()

// Create/Update Routes

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const AuthLazyRoute = AuthLazyImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const DashboardTeacherLazyRoute = DashboardTeacherLazyImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/teacher.lazy').then((d) => d.Route),
)

const DashboardStudentLazyRoute = DashboardStudentLazyImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/student.lazy').then((d) => d.Route),
)

const DashboardCompanyLazyRoute = DashboardCompanyLazyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/company.lazy').then((d) => d.Route),
)

const DashboardAdminLazyRoute = DashboardAdminLazyImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin.lazy').then((d) => d.Route),
)

const AuthResetPasswordLazyRoute = AuthResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/reset-password.lazy').then((d) => d.Route),
)

const AuthOneTimePasswordLazyRoute = AuthOneTimePasswordLazyImport.update({
  id: '/one-time-password',
  path: '/one-time-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/one-time-password.lazy').then((d) => d.Route),
)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

const AuthForgetPasswordLazyRoute = AuthForgetPasswordLazyImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/forget-password.lazy').then((d) => d.Route),
)

const DashboardTeacherSuperviseProjectsLazyRoute =
  DashboardTeacherSuperviseProjectsLazyImport.update({
    id: '/supervise-projects',
    path: '/supervise-projects',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/supervise-projects.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherSubmitProposalLazyRoute =
  DashboardTeacherSubmitProposalLazyImport.update({
    id: '/submit-proposal',
    path: '/submit-proposal',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/submit-proposal.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherSelectSupervisionLazyRoute =
  DashboardTeacherSelectSupervisionLazyImport.update({
    id: '/select-supervision',
    path: '/select-supervision',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/select-supervision.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherPendingRevisionsLazyRoute =
  DashboardTeacherPendingRevisionsLazyImport.update({
    id: '/pending-revisions',
    path: '/pending-revisions',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/pending-revisions.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherManageDefenseScheduleLazyRoute =
  DashboardTeacherManageDefenseScheduleLazyImport.update({
    id: '/manage-defense-schedule',
    path: '/manage-defense-schedule',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/manage-defense-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherDashboardLazyRoute =
  DashboardTeacherDashboardLazyImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/dashboard.lazy').then((d) => d.Route),
  )

const DashboardAdminUserManagmentLazyRoute =
  DashboardAdminUserManagmentLazyImport.update({
    id: '/user-managment',
    path: '/user-managment',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/user-managment.lazy').then((d) => d.Route),
  )

const DashboardAdminSupervisionLazyRoute =
  DashboardAdminSupervisionLazyImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/supervision.lazy').then((d) => d.Route),
  )

const DashboardAdminProjectManagmentLazyRoute =
  DashboardAdminProjectManagmentLazyImport.update({
    id: '/project-managment',
    path: '/project-managment',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/project-managment.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAdminPfeProposalsLazyRoute =
  DashboardAdminPfeProposalsLazyImport.update({
    id: '/pfe-proposals',
    path: '/pfe-proposals',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/pfe-proposals.lazy').then((d) => d.Route),
  )

const DashboardAdminEmailTemplateLazyRoute =
  DashboardAdminEmailTemplateLazyImport.update({
    id: '/email-template',
    path: '/email-template',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/email-template.lazy').then((d) => d.Route),
  )

const DashboardAdminEmailScheduleLazyRoute =
  DashboardAdminEmailScheduleLazyImport.update({
    id: '/email-schedule',
    path: '/email-schedule',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/email-schedule.lazy').then((d) => d.Route),
  )

const DashboardAdminDefenseScheduleLazyRoute =
  DashboardAdminDefenseScheduleLazyImport.update({
    id: '/defense-schedule',
    path: '/defense-schedule',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/defense-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAdminDashboardLazyRoute =
  DashboardAdminDashboardLazyImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/dashboard.lazy').then((d) => d.Route),
  )

const DashboardAdminAddUserLazyRoute = DashboardAdminAddUserLazyImport.update({
  id: '/add-user',
  path: '/add-user',
  getParentRoute: () => DashboardAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/add-user.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/one-time-password': {
      id: '/auth/one-time-password'
      path: '/one-time-password'
      fullPath: '/auth/one-time-password'
      preLoaderRoute: typeof AuthOneTimePasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/company': {
      id: '/dashboard/company'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof DashboardCompanyLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/admin/add-user': {
      id: '/dashboard/admin/add-user'
      path: '/add-user'
      fullPath: '/dashboard/admin/add-user'
      preLoaderRoute: typeof DashboardAdminAddUserLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/dashboard': {
      id: '/dashboard/admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/defense-schedule': {
      id: '/dashboard/admin/defense-schedule'
      path: '/defense-schedule'
      fullPath: '/dashboard/admin/defense-schedule'
      preLoaderRoute: typeof DashboardAdminDefenseScheduleLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/email-schedule': {
      id: '/dashboard/admin/email-schedule'
      path: '/email-schedule'
      fullPath: '/dashboard/admin/email-schedule'
      preLoaderRoute: typeof DashboardAdminEmailScheduleLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/email-template': {
      id: '/dashboard/admin/email-template'
      path: '/email-template'
      fullPath: '/dashboard/admin/email-template'
      preLoaderRoute: typeof DashboardAdminEmailTemplateLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/pfe-proposals': {
      id: '/dashboard/admin/pfe-proposals'
      path: '/pfe-proposals'
      fullPath: '/dashboard/admin/pfe-proposals'
      preLoaderRoute: typeof DashboardAdminPfeProposalsLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/project-managment': {
      id: '/dashboard/admin/project-managment'
      path: '/project-managment'
      fullPath: '/dashboard/admin/project-managment'
      preLoaderRoute: typeof DashboardAdminProjectManagmentLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/supervision': {
      id: '/dashboard/admin/supervision'
      path: '/supervision'
      fullPath: '/dashboard/admin/supervision'
      preLoaderRoute: typeof DashboardAdminSupervisionLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/user-managment': {
      id: '/dashboard/admin/user-managment'
      path: '/user-managment'
      fullPath: '/dashboard/admin/user-managment'
      preLoaderRoute: typeof DashboardAdminUserManagmentLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/teacher/dashboard': {
      id: '/dashboard/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard/teacher/dashboard'
      preLoaderRoute: typeof DashboardTeacherDashboardLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/manage-defense-schedule': {
      id: '/dashboard/teacher/manage-defense-schedule'
      path: '/manage-defense-schedule'
      fullPath: '/dashboard/teacher/manage-defense-schedule'
      preLoaderRoute: typeof DashboardTeacherManageDefenseScheduleLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/pending-revisions': {
      id: '/dashboard/teacher/pending-revisions'
      path: '/pending-revisions'
      fullPath: '/dashboard/teacher/pending-revisions'
      preLoaderRoute: typeof DashboardTeacherPendingRevisionsLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/select-supervision': {
      id: '/dashboard/teacher/select-supervision'
      path: '/select-supervision'
      fullPath: '/dashboard/teacher/select-supervision'
      preLoaderRoute: typeof DashboardTeacherSelectSupervisionLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/submit-proposal': {
      id: '/dashboard/teacher/submit-proposal'
      path: '/submit-proposal'
      fullPath: '/dashboard/teacher/submit-proposal'
      preLoaderRoute: typeof DashboardTeacherSubmitProposalLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/supervise-projects': {
      id: '/dashboard/teacher/supervise-projects'
      path: '/supervise-projects'
      fullPath: '/dashboard/teacher/supervise-projects'
      preLoaderRoute: typeof DashboardTeacherSuperviseProjectsLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
  }
}

// Create and export the route tree

interface AuthLazyRouteChildren {
  AuthForgetPasswordLazyRoute: typeof AuthForgetPasswordLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthOneTimePasswordLazyRoute: typeof AuthOneTimePasswordLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthForgetPasswordLazyRoute: AuthForgetPasswordLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthOneTimePasswordLazyRoute: AuthOneTimePasswordLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

interface DashboardAdminLazyRouteChildren {
  DashboardAdminAddUserLazyRoute: typeof DashboardAdminAddUserLazyRoute
  DashboardAdminDashboardLazyRoute: typeof DashboardAdminDashboardLazyRoute
  DashboardAdminDefenseScheduleLazyRoute: typeof DashboardAdminDefenseScheduleLazyRoute
  DashboardAdminEmailScheduleLazyRoute: typeof DashboardAdminEmailScheduleLazyRoute
  DashboardAdminEmailTemplateLazyRoute: typeof DashboardAdminEmailTemplateLazyRoute
  DashboardAdminPfeProposalsLazyRoute: typeof DashboardAdminPfeProposalsLazyRoute
  DashboardAdminProjectManagmentLazyRoute: typeof DashboardAdminProjectManagmentLazyRoute
  DashboardAdminSupervisionLazyRoute: typeof DashboardAdminSupervisionLazyRoute
  DashboardAdminUserManagmentLazyRoute: typeof DashboardAdminUserManagmentLazyRoute
}

const DashboardAdminLazyRouteChildren: DashboardAdminLazyRouteChildren = {
  DashboardAdminAddUserLazyRoute: DashboardAdminAddUserLazyRoute,
  DashboardAdminDashboardLazyRoute: DashboardAdminDashboardLazyRoute,
  DashboardAdminDefenseScheduleLazyRoute:
    DashboardAdminDefenseScheduleLazyRoute,
  DashboardAdminEmailScheduleLazyRoute: DashboardAdminEmailScheduleLazyRoute,
  DashboardAdminEmailTemplateLazyRoute: DashboardAdminEmailTemplateLazyRoute,
  DashboardAdminPfeProposalsLazyRoute: DashboardAdminPfeProposalsLazyRoute,
  DashboardAdminProjectManagmentLazyRoute:
    DashboardAdminProjectManagmentLazyRoute,
  DashboardAdminSupervisionLazyRoute: DashboardAdminSupervisionLazyRoute,
  DashboardAdminUserManagmentLazyRoute: DashboardAdminUserManagmentLazyRoute,
}

const DashboardAdminLazyRouteWithChildren =
  DashboardAdminLazyRoute._addFileChildren(DashboardAdminLazyRouteChildren)

interface DashboardTeacherLazyRouteChildren {
  DashboardTeacherDashboardLazyRoute: typeof DashboardTeacherDashboardLazyRoute
  DashboardTeacherManageDefenseScheduleLazyRoute: typeof DashboardTeacherManageDefenseScheduleLazyRoute
  DashboardTeacherPendingRevisionsLazyRoute: typeof DashboardTeacherPendingRevisionsLazyRoute
  DashboardTeacherSelectSupervisionLazyRoute: typeof DashboardTeacherSelectSupervisionLazyRoute
  DashboardTeacherSubmitProposalLazyRoute: typeof DashboardTeacherSubmitProposalLazyRoute
  DashboardTeacherSuperviseProjectsLazyRoute: typeof DashboardTeacherSuperviseProjectsLazyRoute
}

const DashboardTeacherLazyRouteChildren: DashboardTeacherLazyRouteChildren = {
  DashboardTeacherDashboardLazyRoute: DashboardTeacherDashboardLazyRoute,
  DashboardTeacherManageDefenseScheduleLazyRoute:
    DashboardTeacherManageDefenseScheduleLazyRoute,
  DashboardTeacherPendingRevisionsLazyRoute:
    DashboardTeacherPendingRevisionsLazyRoute,
  DashboardTeacherSelectSupervisionLazyRoute:
    DashboardTeacherSelectSupervisionLazyRoute,
  DashboardTeacherSubmitProposalLazyRoute:
    DashboardTeacherSubmitProposalLazyRoute,
  DashboardTeacherSuperviseProjectsLazyRoute:
    DashboardTeacherSuperviseProjectsLazyRoute,
}

const DashboardTeacherLazyRouteWithChildren =
  DashboardTeacherLazyRoute._addFileChildren(DashboardTeacherLazyRouteChildren)

interface DashboardLazyRouteChildren {
  DashboardAdminLazyRoute: typeof DashboardAdminLazyRouteWithChildren
  DashboardCompanyLazyRoute: typeof DashboardCompanyLazyRoute
  DashboardStudentLazyRoute: typeof DashboardStudentLazyRoute
  DashboardTeacherLazyRoute: typeof DashboardTeacherLazyRouteWithChildren
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardAdminLazyRoute: DashboardAdminLazyRouteWithChildren,
  DashboardCompanyLazyRoute: DashboardCompanyLazyRoute,
  DashboardStudentLazyRoute: DashboardStudentLazyRoute,
  DashboardTeacherLazyRoute: DashboardTeacherLazyRouteWithChildren,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRoute
  '/dashboard/student': typeof DashboardStudentLazyRoute
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-managment': typeof DashboardAdminUserManagmentLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/select-supervision': typeof DashboardTeacherSelectSupervisionLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRoute
  '/dashboard/student': typeof DashboardStudentLazyRoute
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-managment': typeof DashboardAdminUserManagmentLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/select-supervision': typeof DashboardTeacherSelectSupervisionLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRoute
  '/dashboard/student': typeof DashboardStudentLazyRoute
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-managment': typeof DashboardAdminUserManagmentLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/select-supervision': typeof DashboardTeacherSelectSupervisionLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-managment'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/select-supervision'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-managment'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/select-supervision'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-managment'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/select-supervision'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthLazyRoute: AuthLazyRouteWithChildren,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth": {
      "filePath": "auth.lazy.tsx",
      "children": [
        "/auth/forget-password",
        "/auth/login",
        "/auth/one-time-password",
        "/auth/reset-password"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx",
      "children": [
        "/dashboard/admin",
        "/dashboard/company",
        "/dashboard/student",
        "/dashboard/teacher",
        "/dashboard/"
      ]
    },
    "/auth/forget-password": {
      "filePath": "auth/forget-password.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/one-time-password": {
      "filePath": "auth/one-time-password.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.lazy.tsx",
      "parent": "/auth"
    },
    "/dashboard/admin": {
      "filePath": "dashboard/admin.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/admin/add-user",
        "/dashboard/admin/dashboard",
        "/dashboard/admin/defense-schedule",
        "/dashboard/admin/email-schedule",
        "/dashboard/admin/email-template",
        "/dashboard/admin/pfe-proposals",
        "/dashboard/admin/project-managment",
        "/dashboard/admin/supervision",
        "/dashboard/admin/user-managment"
      ]
    },
    "/dashboard/company": {
      "filePath": "dashboard/company.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/student": {
      "filePath": "dashboard/student.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/teacher": {
      "filePath": "dashboard/teacher.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/teacher/dashboard",
        "/dashboard/teacher/manage-defense-schedule",
        "/dashboard/teacher/pending-revisions",
        "/dashboard/teacher/select-supervision",
        "/dashboard/teacher/submit-proposal",
        "/dashboard/teacher/supervise-projects"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/admin/add-user": {
      "filePath": "dashboard/admin/add-user.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/dashboard": {
      "filePath": "dashboard/admin/dashboard.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/defense-schedule": {
      "filePath": "dashboard/admin/defense-schedule.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/email-schedule": {
      "filePath": "dashboard/admin/email-schedule.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/email-template": {
      "filePath": "dashboard/admin/email-template.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/pfe-proposals": {
      "filePath": "dashboard/admin/pfe-proposals.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/project-managment": {
      "filePath": "dashboard/admin/project-managment.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/supervision": {
      "filePath": "dashboard/admin/supervision.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/user-managment": {
      "filePath": "dashboard/admin/user-managment.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/teacher/dashboard": {
      "filePath": "dashboard/teacher/dashboard.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/manage-defense-schedule": {
      "filePath": "dashboard/teacher/manage-defense-schedule.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/pending-revisions": {
      "filePath": "dashboard/teacher/pending-revisions.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/select-supervision": {
      "filePath": "dashboard/teacher/select-supervision.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/submit-proposal": {
      "filePath": "dashboard/teacher/submit-proposal.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/supervise-projects": {
      "filePath": "dashboard/teacher/supervise-projects.lazy.tsx",
      "parent": "/dashboard/teacher"
    }
  }
}
ROUTE_MANIFEST_END */
