/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as DashboardAdminImport } from './routes/dashboard/admin'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const AuthResetPasswordLazyImport = createFileRoute('/auth/reset-password')()
const AuthOneTimePasswordLazyImport = createFileRoute(
  '/auth/one-time-password',
)()
const AuthLoginLazyImport = createFileRoute('/auth/login')()
const AuthForgetPasswordLazyImport = createFileRoute('/auth/forget-password')()
const DashboardAdminIndexLazyImport = createFileRoute('/dashboard/admin/')()
const DashboardAdminAddUserLazyImport = createFileRoute(
  '/dashboard/admin/add-user',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const AuthResetPasswordLazyRoute = AuthResetPasswordLazyImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/reset-password.lazy').then((d) => d.Route),
)

const AuthOneTimePasswordLazyRoute = AuthOneTimePasswordLazyImport.update({
  id: '/auth/one-time-password',
  path: '/auth/one-time-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/one-time-password.lazy').then((d) => d.Route),
)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

const AuthForgetPasswordLazyRoute = AuthForgetPasswordLazyImport.update({
  id: '/auth/forget-password',
  path: '/auth/forget-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/forget-password.lazy').then((d) => d.Route),
)

const DashboardAdminRoute = DashboardAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAdminIndexLazyRoute = DashboardAdminIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/index.lazy').then((d) => d.Route),
)

const DashboardAdminAddUserLazyRoute = DashboardAdminAddUserLazyImport.update({
  id: '/add-user',
  path: '/add-user',
  getParentRoute: () => DashboardAdminRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/add-user.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminImport
      parentRoute: typeof DashboardImport
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/one-time-password': {
      id: '/auth/one-time-password'
      path: '/auth/one-time-password'
      fullPath: '/auth/one-time-password'
      preLoaderRoute: typeof AuthOneTimePasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/admin/add-user': {
      id: '/dashboard/admin/add-user'
      path: '/add-user'
      fullPath: '/dashboard/admin/add-user'
      preLoaderRoute: typeof DashboardAdminAddUserLazyImport
      parentRoute: typeof DashboardAdminImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexLazyImport
      parentRoute: typeof DashboardAdminImport
    }
  }
}

// Create and export the route tree

interface DashboardAdminRouteChildren {
  DashboardAdminAddUserLazyRoute: typeof DashboardAdminAddUserLazyRoute
  DashboardAdminIndexLazyRoute: typeof DashboardAdminIndexLazyRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAddUserLazyRoute: DashboardAdminAddUserLazyRoute,
  DashboardAdminIndexLazyRoute: DashboardAdminIndexLazyRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/': typeof DashboardAdminIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin': typeof DashboardAdminIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/': typeof DashboardAdminIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgetPasswordLazyRoute: typeof AuthForgetPasswordLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthOneTimePasswordLazyRoute: typeof AuthOneTimePasswordLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgetPasswordLazyRoute: AuthForgetPasswordLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthOneTimePasswordLazyRoute: AuthOneTimePasswordLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/auth/forget-password",
        "/auth/login",
        "/auth/one-time-password",
        "/auth/reset-password"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/admin",
        "/dashboard/"
      ]
    },
    "/dashboard/admin": {
      "filePath": "dashboard/admin.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/admin/add-user",
        "/dashboard/admin/"
      ]
    },
    "/auth/forget-password": {
      "filePath": "auth/forget-password.lazy.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx"
    },
    "/auth/one-time-password": {
      "filePath": "auth/one-time-password.lazy.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/admin/add-user": {
      "filePath": "dashboard/admin/add-user.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/": {
      "filePath": "dashboard/admin/index.lazy.tsx",
      "parent": "/dashboard/admin"
    }
  }
}
ROUTE_MANIFEST_END */
