/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const OwnerLazyImport = createFileRoute('/owner')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const AuthLazyImport = createFileRoute('/auth')()
const IndexLazyImport = createFileRoute('/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const OwnerOwnerLazyImport = createFileRoute('/owner/owner')()
const DashboardTeacherLazyImport = createFileRoute('/dashboard/teacher')()
const DashboardStudentLazyImport = createFileRoute('/dashboard/student')()
const DashboardCompanyLazyImport = createFileRoute('/dashboard/company')()
const DashboardAdminLazyImport = createFileRoute('/dashboard/admin')()
const AuthResetPasswordLazyImport = createFileRoute('/auth/reset-password')()
const AuthOneTimePasswordLazyImport = createFileRoute(
  '/auth/one-time-password',
)()
const AuthLoginLazyImport = createFileRoute('/auth/login')()
const AuthForgetPasswordLazyImport = createFileRoute('/auth/forget-password')()
const DashboardTeacherSuperviseProjectsLazyImport = createFileRoute(
  '/dashboard/teacher/supervise-projects',
)()
const DashboardTeacherSubmitProposalLazyImport = createFileRoute(
  '/dashboard/teacher/submit-proposal',
)()
const DashboardTeacherPendingRevisionsLazyImport = createFileRoute(
  '/dashboard/teacher/pending-revisions',
)()
const DashboardTeacherMySupervisedProjectsLazyImport = createFileRoute(
  '/dashboard/teacher/my-supervised-projects',
)()
const DashboardTeacherManageDefenseScheduleLazyImport = createFileRoute(
  '/dashboard/teacher/manage-defense-schedule',
)()
const DashboardTeacherDefenseSelctionLazyImport = createFileRoute(
  '/dashboard/teacher/defense-selction',
)()
const DashboardTeacherDashboardLazyImport = createFileRoute(
  '/dashboard/teacher/dashboard',
)()
const DashboardTeacherArchiveLazyImport = createFileRoute(
  '/dashboard/teacher/archive',
)()
const DashboardStudentSuggestedTopicsLazyImport = createFileRoute(
  '/dashboard/student/suggested-topics',
)()
const DashboardStudentProposeTopicLazyImport = createFileRoute(
  '/dashboard/student/propose-topic',
)()
const DashboardStudentMyProjectsLazyImport = createFileRoute(
  '/dashboard/student/my-projects',
)()
const DashboardStudentHomepageLazyImport = createFileRoute(
  '/dashboard/student/homepage',
)()
const DashboardCompanyProposeTopicsLazyImport = createFileRoute(
  '/dashboard/company/propose-topics',
)()
const DashboardCompanyMyProjectsLazyImport = createFileRoute(
  '/dashboard/company/my-projects',
)()
const DashboardCompanyHomepageLazyImport = createFileRoute(
  '/dashboard/company/homepage',
)()
const DashboardAdminUserManagementLazyImport = createFileRoute(
  '/dashboard/admin/user-management',
)()
const DashboardAdminSupervisionLazyImport = createFileRoute(
  '/dashboard/admin/supervision',
)()
const DashboardAdminRoomsLazyImport = createFileRoute(
  '/dashboard/admin/rooms',
)()
const DashboardAdminProjectManagmentLazyImport = createFileRoute(
  '/dashboard/admin/project-managment',
)()
const DashboardAdminPfeProposalsLazyImport = createFileRoute(
  '/dashboard/admin/pfe-proposals',
)()
const DashboardAdminEmailTemplateLazyImport = createFileRoute(
  '/dashboard/admin/email-template',
)()
const DashboardAdminEmailScheduleLazyImport = createFileRoute(
  '/dashboard/admin/email-schedule',
)()
const DashboardAdminDefenseScheduleLazyImport = createFileRoute(
  '/dashboard/admin/defense-schedule',
)()
const DashboardAdminDashboardLazyImport = createFileRoute(
  '/dashboard/admin/dashboard',
)()
const DashboardAdminArchiveLazyImport = createFileRoute(
  '/dashboard/admin/archive',
)()
const DashboardAdminAddUserLazyImport = createFileRoute(
  '/dashboard/admin/add-user',
)()

// Create/Update Routes

const OwnerLazyRoute = OwnerLazyImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/owner.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const AuthLazyRoute = AuthLazyImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const OwnerOwnerLazyRoute = OwnerOwnerLazyImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => OwnerLazyRoute,
} as any).lazy(() => import('./routes/owner/owner.lazy').then((d) => d.Route))

const DashboardTeacherLazyRoute = DashboardTeacherLazyImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/teacher.lazy').then((d) => d.Route),
)

const DashboardStudentLazyRoute = DashboardStudentLazyImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/student.lazy').then((d) => d.Route),
)

const DashboardCompanyLazyRoute = DashboardCompanyLazyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/company.lazy').then((d) => d.Route),
)

const DashboardAdminLazyRoute = DashboardAdminLazyImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin.lazy').then((d) => d.Route),
)

const AuthResetPasswordLazyRoute = AuthResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/reset-password.lazy').then((d) => d.Route),
)

const AuthOneTimePasswordLazyRoute = AuthOneTimePasswordLazyImport.update({
  id: '/one-time-password',
  path: '/one-time-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/one-time-password.lazy').then((d) => d.Route),
)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

const AuthForgetPasswordLazyRoute = AuthForgetPasswordLazyImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthLazyRoute,
} as any).lazy(() =>
  import('./routes/auth/forget-password.lazy').then((d) => d.Route),
)

const DashboardTeacherSuperviseProjectsLazyRoute =
  DashboardTeacherSuperviseProjectsLazyImport.update({
    id: '/supervise-projects',
    path: '/supervise-projects',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/supervise-projects.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherSubmitProposalLazyRoute =
  DashboardTeacherSubmitProposalLazyImport.update({
    id: '/submit-proposal',
    path: '/submit-proposal',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/submit-proposal.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherPendingRevisionsLazyRoute =
  DashboardTeacherPendingRevisionsLazyImport.update({
    id: '/pending-revisions',
    path: '/pending-revisions',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/pending-revisions.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherMySupervisedProjectsLazyRoute =
  DashboardTeacherMySupervisedProjectsLazyImport.update({
    id: '/my-supervised-projects',
    path: '/my-supervised-projects',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/my-supervised-projects.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherManageDefenseScheduleLazyRoute =
  DashboardTeacherManageDefenseScheduleLazyImport.update({
    id: '/manage-defense-schedule',
    path: '/manage-defense-schedule',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/manage-defense-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherDefenseSelctionLazyRoute =
  DashboardTeacherDefenseSelctionLazyImport.update({
    id: '/defense-selction',
    path: '/defense-selction',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/defense-selction.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardTeacherDashboardLazyRoute =
  DashboardTeacherDashboardLazyImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/dashboard.lazy').then((d) => d.Route),
  )

const DashboardTeacherArchiveLazyRoute =
  DashboardTeacherArchiveLazyImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => DashboardTeacherLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/teacher/archive.lazy').then((d) => d.Route),
  )

const DashboardStudentSuggestedTopicsLazyRoute =
  DashboardStudentSuggestedTopicsLazyImport.update({
    id: '/suggested-topics',
    path: '/suggested-topics',
    getParentRoute: () => DashboardStudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/student/suggested-topics.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardStudentProposeTopicLazyRoute =
  DashboardStudentProposeTopicLazyImport.update({
    id: '/propose-topic',
    path: '/propose-topic',
    getParentRoute: () => DashboardStudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/student/propose-topic.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardStudentMyProjectsLazyRoute =
  DashboardStudentMyProjectsLazyImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => DashboardStudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/student/my-projects.lazy').then((d) => d.Route),
  )

const DashboardStudentHomepageLazyRoute =
  DashboardStudentHomepageLazyImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => DashboardStudentLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/student/homepage.lazy').then((d) => d.Route),
  )

const DashboardCompanyProposeTopicsLazyRoute =
  DashboardCompanyProposeTopicsLazyImport.update({
    id: '/propose-topics',
    path: '/propose-topics',
    getParentRoute: () => DashboardCompanyLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/company/propose-topics.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardCompanyMyProjectsLazyRoute =
  DashboardCompanyMyProjectsLazyImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => DashboardCompanyLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/company/my-projects.lazy').then((d) => d.Route),
  )

const DashboardCompanyHomepageLazyRoute =
  DashboardCompanyHomepageLazyImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => DashboardCompanyLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/company/homepage.lazy').then((d) => d.Route),
  )

const DashboardAdminUserManagementLazyRoute =
  DashboardAdminUserManagementLazyImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/user-management.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAdminSupervisionLazyRoute =
  DashboardAdminSupervisionLazyImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/supervision.lazy').then((d) => d.Route),
  )

const DashboardAdminRoomsLazyRoute = DashboardAdminRoomsLazyImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/rooms.lazy').then((d) => d.Route),
)

const DashboardAdminProjectManagmentLazyRoute =
  DashboardAdminProjectManagmentLazyImport.update({
    id: '/project-managment',
    path: '/project-managment',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/project-managment.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAdminPfeProposalsLazyRoute =
  DashboardAdminPfeProposalsLazyImport.update({
    id: '/pfe-proposals',
    path: '/pfe-proposals',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/pfe-proposals.lazy').then((d) => d.Route),
  )

const DashboardAdminEmailTemplateLazyRoute =
  DashboardAdminEmailTemplateLazyImport.update({
    id: '/email-template',
    path: '/email-template',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/email-template.lazy').then((d) => d.Route),
  )

const DashboardAdminEmailScheduleLazyRoute =
  DashboardAdminEmailScheduleLazyImport.update({
    id: '/email-schedule',
    path: '/email-schedule',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/email-schedule.lazy').then((d) => d.Route),
  )

const DashboardAdminDefenseScheduleLazyRoute =
  DashboardAdminDefenseScheduleLazyImport.update({
    id: '/defense-schedule',
    path: '/defense-schedule',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/defense-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardAdminDashboardLazyRoute =
  DashboardAdminDashboardLazyImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardAdminLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/admin/dashboard.lazy').then((d) => d.Route),
  )

const DashboardAdminArchiveLazyRoute = DashboardAdminArchiveLazyImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => DashboardAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/archive.lazy').then((d) => d.Route),
)

const DashboardAdminAddUserLazyRoute = DashboardAdminAddUserLazyImport.update({
  id: '/add-user',
  path: '/add-user',
  getParentRoute: () => DashboardAdminLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/add-user.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/one-time-password': {
      id: '/auth/one-time-password'
      path: '/one-time-password'
      fullPath: '/auth/one-time-password'
      preLoaderRoute: typeof AuthOneTimePasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordLazyImport
      parentRoute: typeof AuthLazyImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/company': {
      id: '/dashboard/company'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof DashboardCompanyLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/owner/owner': {
      id: '/owner/owner'
      path: '/owner'
      fullPath: '/owner/owner'
      preLoaderRoute: typeof OwnerOwnerLazyImport
      parentRoute: typeof OwnerLazyImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/admin/add-user': {
      id: '/dashboard/admin/add-user'
      path: '/add-user'
      fullPath: '/dashboard/admin/add-user'
      preLoaderRoute: typeof DashboardAdminAddUserLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/archive': {
      id: '/dashboard/admin/archive'
      path: '/archive'
      fullPath: '/dashboard/admin/archive'
      preLoaderRoute: typeof DashboardAdminArchiveLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/dashboard': {
      id: '/dashboard/admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/defense-schedule': {
      id: '/dashboard/admin/defense-schedule'
      path: '/defense-schedule'
      fullPath: '/dashboard/admin/defense-schedule'
      preLoaderRoute: typeof DashboardAdminDefenseScheduleLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/email-schedule': {
      id: '/dashboard/admin/email-schedule'
      path: '/email-schedule'
      fullPath: '/dashboard/admin/email-schedule'
      preLoaderRoute: typeof DashboardAdminEmailScheduleLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/email-template': {
      id: '/dashboard/admin/email-template'
      path: '/email-template'
      fullPath: '/dashboard/admin/email-template'
      preLoaderRoute: typeof DashboardAdminEmailTemplateLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/pfe-proposals': {
      id: '/dashboard/admin/pfe-proposals'
      path: '/pfe-proposals'
      fullPath: '/dashboard/admin/pfe-proposals'
      preLoaderRoute: typeof DashboardAdminPfeProposalsLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/project-managment': {
      id: '/dashboard/admin/project-managment'
      path: '/project-managment'
      fullPath: '/dashboard/admin/project-managment'
      preLoaderRoute: typeof DashboardAdminProjectManagmentLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/rooms': {
      id: '/dashboard/admin/rooms'
      path: '/rooms'
      fullPath: '/dashboard/admin/rooms'
      preLoaderRoute: typeof DashboardAdminRoomsLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/supervision': {
      id: '/dashboard/admin/supervision'
      path: '/supervision'
      fullPath: '/dashboard/admin/supervision'
      preLoaderRoute: typeof DashboardAdminSupervisionLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/admin/user-management': {
      id: '/dashboard/admin/user-management'
      path: '/user-management'
      fullPath: '/dashboard/admin/user-management'
      preLoaderRoute: typeof DashboardAdminUserManagementLazyImport
      parentRoute: typeof DashboardAdminLazyImport
    }
    '/dashboard/company/homepage': {
      id: '/dashboard/company/homepage'
      path: '/homepage'
      fullPath: '/dashboard/company/homepage'
      preLoaderRoute: typeof DashboardCompanyHomepageLazyImport
      parentRoute: typeof DashboardCompanyLazyImport
    }
    '/dashboard/company/my-projects': {
      id: '/dashboard/company/my-projects'
      path: '/my-projects'
      fullPath: '/dashboard/company/my-projects'
      preLoaderRoute: typeof DashboardCompanyMyProjectsLazyImport
      parentRoute: typeof DashboardCompanyLazyImport
    }
    '/dashboard/company/propose-topics': {
      id: '/dashboard/company/propose-topics'
      path: '/propose-topics'
      fullPath: '/dashboard/company/propose-topics'
      preLoaderRoute: typeof DashboardCompanyProposeTopicsLazyImport
      parentRoute: typeof DashboardCompanyLazyImport
    }
    '/dashboard/student/homepage': {
      id: '/dashboard/student/homepage'
      path: '/homepage'
      fullPath: '/dashboard/student/homepage'
      preLoaderRoute: typeof DashboardStudentHomepageLazyImport
      parentRoute: typeof DashboardStudentLazyImport
    }
    '/dashboard/student/my-projects': {
      id: '/dashboard/student/my-projects'
      path: '/my-projects'
      fullPath: '/dashboard/student/my-projects'
      preLoaderRoute: typeof DashboardStudentMyProjectsLazyImport
      parentRoute: typeof DashboardStudentLazyImport
    }
    '/dashboard/student/propose-topic': {
      id: '/dashboard/student/propose-topic'
      path: '/propose-topic'
      fullPath: '/dashboard/student/propose-topic'
      preLoaderRoute: typeof DashboardStudentProposeTopicLazyImport
      parentRoute: typeof DashboardStudentLazyImport
    }
    '/dashboard/student/suggested-topics': {
      id: '/dashboard/student/suggested-topics'
      path: '/suggested-topics'
      fullPath: '/dashboard/student/suggested-topics'
      preLoaderRoute: typeof DashboardStudentSuggestedTopicsLazyImport
      parentRoute: typeof DashboardStudentLazyImport
    }
    '/dashboard/teacher/archive': {
      id: '/dashboard/teacher/archive'
      path: '/archive'
      fullPath: '/dashboard/teacher/archive'
      preLoaderRoute: typeof DashboardTeacherArchiveLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/dashboard': {
      id: '/dashboard/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard/teacher/dashboard'
      preLoaderRoute: typeof DashboardTeacherDashboardLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/defense-selction': {
      id: '/dashboard/teacher/defense-selction'
      path: '/defense-selction'
      fullPath: '/dashboard/teacher/defense-selction'
      preLoaderRoute: typeof DashboardTeacherDefenseSelctionLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/manage-defense-schedule': {
      id: '/dashboard/teacher/manage-defense-schedule'
      path: '/manage-defense-schedule'
      fullPath: '/dashboard/teacher/manage-defense-schedule'
      preLoaderRoute: typeof DashboardTeacherManageDefenseScheduleLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/my-supervised-projects': {
      id: '/dashboard/teacher/my-supervised-projects'
      path: '/my-supervised-projects'
      fullPath: '/dashboard/teacher/my-supervised-projects'
      preLoaderRoute: typeof DashboardTeacherMySupervisedProjectsLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/pending-revisions': {
      id: '/dashboard/teacher/pending-revisions'
      path: '/pending-revisions'
      fullPath: '/dashboard/teacher/pending-revisions'
      preLoaderRoute: typeof DashboardTeacherPendingRevisionsLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/submit-proposal': {
      id: '/dashboard/teacher/submit-proposal'
      path: '/submit-proposal'
      fullPath: '/dashboard/teacher/submit-proposal'
      preLoaderRoute: typeof DashboardTeacherSubmitProposalLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
    '/dashboard/teacher/supervise-projects': {
      id: '/dashboard/teacher/supervise-projects'
      path: '/supervise-projects'
      fullPath: '/dashboard/teacher/supervise-projects'
      preLoaderRoute: typeof DashboardTeacherSuperviseProjectsLazyImport
      parentRoute: typeof DashboardTeacherLazyImport
    }
  }
}

// Create and export the route tree

interface AuthLazyRouteChildren {
  AuthForgetPasswordLazyRoute: typeof AuthForgetPasswordLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthOneTimePasswordLazyRoute: typeof AuthOneTimePasswordLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
}

const AuthLazyRouteChildren: AuthLazyRouteChildren = {
  AuthForgetPasswordLazyRoute: AuthForgetPasswordLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthOneTimePasswordLazyRoute: AuthOneTimePasswordLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
}

const AuthLazyRouteWithChildren = AuthLazyRoute._addFileChildren(
  AuthLazyRouteChildren,
)

interface DashboardAdminLazyRouteChildren {
  DashboardAdminAddUserLazyRoute: typeof DashboardAdminAddUserLazyRoute
  DashboardAdminArchiveLazyRoute: typeof DashboardAdminArchiveLazyRoute
  DashboardAdminDashboardLazyRoute: typeof DashboardAdminDashboardLazyRoute
  DashboardAdminDefenseScheduleLazyRoute: typeof DashboardAdminDefenseScheduleLazyRoute
  DashboardAdminEmailScheduleLazyRoute: typeof DashboardAdminEmailScheduleLazyRoute
  DashboardAdminEmailTemplateLazyRoute: typeof DashboardAdminEmailTemplateLazyRoute
  DashboardAdminPfeProposalsLazyRoute: typeof DashboardAdminPfeProposalsLazyRoute
  DashboardAdminProjectManagmentLazyRoute: typeof DashboardAdminProjectManagmentLazyRoute
  DashboardAdminRoomsLazyRoute: typeof DashboardAdminRoomsLazyRoute
  DashboardAdminSupervisionLazyRoute: typeof DashboardAdminSupervisionLazyRoute
  DashboardAdminUserManagementLazyRoute: typeof DashboardAdminUserManagementLazyRoute
}

const DashboardAdminLazyRouteChildren: DashboardAdminLazyRouteChildren = {
  DashboardAdminAddUserLazyRoute: DashboardAdminAddUserLazyRoute,
  DashboardAdminArchiveLazyRoute: DashboardAdminArchiveLazyRoute,
  DashboardAdminDashboardLazyRoute: DashboardAdminDashboardLazyRoute,
  DashboardAdminDefenseScheduleLazyRoute:
    DashboardAdminDefenseScheduleLazyRoute,
  DashboardAdminEmailScheduleLazyRoute: DashboardAdminEmailScheduleLazyRoute,
  DashboardAdminEmailTemplateLazyRoute: DashboardAdminEmailTemplateLazyRoute,
  DashboardAdminPfeProposalsLazyRoute: DashboardAdminPfeProposalsLazyRoute,
  DashboardAdminProjectManagmentLazyRoute:
    DashboardAdminProjectManagmentLazyRoute,
  DashboardAdminRoomsLazyRoute: DashboardAdminRoomsLazyRoute,
  DashboardAdminSupervisionLazyRoute: DashboardAdminSupervisionLazyRoute,
  DashboardAdminUserManagementLazyRoute: DashboardAdminUserManagementLazyRoute,
}

const DashboardAdminLazyRouteWithChildren =
  DashboardAdminLazyRoute._addFileChildren(DashboardAdminLazyRouteChildren)

interface DashboardCompanyLazyRouteChildren {
  DashboardCompanyHomepageLazyRoute: typeof DashboardCompanyHomepageLazyRoute
  DashboardCompanyMyProjectsLazyRoute: typeof DashboardCompanyMyProjectsLazyRoute
  DashboardCompanyProposeTopicsLazyRoute: typeof DashboardCompanyProposeTopicsLazyRoute
}

const DashboardCompanyLazyRouteChildren: DashboardCompanyLazyRouteChildren = {
  DashboardCompanyHomepageLazyRoute: DashboardCompanyHomepageLazyRoute,
  DashboardCompanyMyProjectsLazyRoute: DashboardCompanyMyProjectsLazyRoute,
  DashboardCompanyProposeTopicsLazyRoute:
    DashboardCompanyProposeTopicsLazyRoute,
}

const DashboardCompanyLazyRouteWithChildren =
  DashboardCompanyLazyRoute._addFileChildren(DashboardCompanyLazyRouteChildren)

interface DashboardStudentLazyRouteChildren {
  DashboardStudentHomepageLazyRoute: typeof DashboardStudentHomepageLazyRoute
  DashboardStudentMyProjectsLazyRoute: typeof DashboardStudentMyProjectsLazyRoute
  DashboardStudentProposeTopicLazyRoute: typeof DashboardStudentProposeTopicLazyRoute
  DashboardStudentSuggestedTopicsLazyRoute: typeof DashboardStudentSuggestedTopicsLazyRoute
}

const DashboardStudentLazyRouteChildren: DashboardStudentLazyRouteChildren = {
  DashboardStudentHomepageLazyRoute: DashboardStudentHomepageLazyRoute,
  DashboardStudentMyProjectsLazyRoute: DashboardStudentMyProjectsLazyRoute,
  DashboardStudentProposeTopicLazyRoute: DashboardStudentProposeTopicLazyRoute,
  DashboardStudentSuggestedTopicsLazyRoute:
    DashboardStudentSuggestedTopicsLazyRoute,
}

const DashboardStudentLazyRouteWithChildren =
  DashboardStudentLazyRoute._addFileChildren(DashboardStudentLazyRouteChildren)

interface DashboardTeacherLazyRouteChildren {
  DashboardTeacherArchiveLazyRoute: typeof DashboardTeacherArchiveLazyRoute
  DashboardTeacherDashboardLazyRoute: typeof DashboardTeacherDashboardLazyRoute
  DashboardTeacherDefenseSelctionLazyRoute: typeof DashboardTeacherDefenseSelctionLazyRoute
  DashboardTeacherManageDefenseScheduleLazyRoute: typeof DashboardTeacherManageDefenseScheduleLazyRoute
  DashboardTeacherMySupervisedProjectsLazyRoute: typeof DashboardTeacherMySupervisedProjectsLazyRoute
  DashboardTeacherPendingRevisionsLazyRoute: typeof DashboardTeacherPendingRevisionsLazyRoute
  DashboardTeacherSubmitProposalLazyRoute: typeof DashboardTeacherSubmitProposalLazyRoute
  DashboardTeacherSuperviseProjectsLazyRoute: typeof DashboardTeacherSuperviseProjectsLazyRoute
}

const DashboardTeacherLazyRouteChildren: DashboardTeacherLazyRouteChildren = {
  DashboardTeacherArchiveLazyRoute: DashboardTeacherArchiveLazyRoute,
  DashboardTeacherDashboardLazyRoute: DashboardTeacherDashboardLazyRoute,
  DashboardTeacherDefenseSelctionLazyRoute:
    DashboardTeacherDefenseSelctionLazyRoute,
  DashboardTeacherManageDefenseScheduleLazyRoute:
    DashboardTeacherManageDefenseScheduleLazyRoute,
  DashboardTeacherMySupervisedProjectsLazyRoute:
    DashboardTeacherMySupervisedProjectsLazyRoute,
  DashboardTeacherPendingRevisionsLazyRoute:
    DashboardTeacherPendingRevisionsLazyRoute,
  DashboardTeacherSubmitProposalLazyRoute:
    DashboardTeacherSubmitProposalLazyRoute,
  DashboardTeacherSuperviseProjectsLazyRoute:
    DashboardTeacherSuperviseProjectsLazyRoute,
}

const DashboardTeacherLazyRouteWithChildren =
  DashboardTeacherLazyRoute._addFileChildren(DashboardTeacherLazyRouteChildren)

interface DashboardLazyRouteChildren {
  DashboardAdminLazyRoute: typeof DashboardAdminLazyRouteWithChildren
  DashboardCompanyLazyRoute: typeof DashboardCompanyLazyRouteWithChildren
  DashboardStudentLazyRoute: typeof DashboardStudentLazyRouteWithChildren
  DashboardTeacherLazyRoute: typeof DashboardTeacherLazyRouteWithChildren
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardAdminLazyRoute: DashboardAdminLazyRouteWithChildren,
  DashboardCompanyLazyRoute: DashboardCompanyLazyRouteWithChildren,
  DashboardStudentLazyRoute: DashboardStudentLazyRouteWithChildren,
  DashboardTeacherLazyRoute: DashboardTeacherLazyRouteWithChildren,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

interface OwnerLazyRouteChildren {
  OwnerOwnerLazyRoute: typeof OwnerOwnerLazyRoute
}

const OwnerLazyRouteChildren: OwnerLazyRouteChildren = {
  OwnerOwnerLazyRoute: OwnerOwnerLazyRoute,
}

const OwnerLazyRouteWithChildren = OwnerLazyRoute._addFileChildren(
  OwnerLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/owner': typeof OwnerLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRouteWithChildren
  '/dashboard/student': typeof DashboardStudentLazyRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/owner/owner': typeof OwnerOwnerLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/archive': typeof DashboardAdminArchiveLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-management': typeof DashboardAdminUserManagementLazyRoute
  '/dashboard/company/homepage': typeof DashboardCompanyHomepageLazyRoute
  '/dashboard/company/my-projects': typeof DashboardCompanyMyProjectsLazyRoute
  '/dashboard/company/propose-topics': typeof DashboardCompanyProposeTopicsLazyRoute
  '/dashboard/student/homepage': typeof DashboardStudentHomepageLazyRoute
  '/dashboard/student/my-projects': typeof DashboardStudentMyProjectsLazyRoute
  '/dashboard/student/propose-topic': typeof DashboardStudentProposeTopicLazyRoute
  '/dashboard/student/suggested-topics': typeof DashboardStudentSuggestedTopicsLazyRoute
  '/dashboard/teacher/archive': typeof DashboardTeacherArchiveLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/defense-selction': typeof DashboardTeacherDefenseSelctionLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/my-supervised-projects': typeof DashboardTeacherMySupervisedProjectsLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/owner': typeof OwnerLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRouteWithChildren
  '/dashboard/student': typeof DashboardStudentLazyRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/owner/owner': typeof OwnerOwnerLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/archive': typeof DashboardAdminArchiveLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-management': typeof DashboardAdminUserManagementLazyRoute
  '/dashboard/company/homepage': typeof DashboardCompanyHomepageLazyRoute
  '/dashboard/company/my-projects': typeof DashboardCompanyMyProjectsLazyRoute
  '/dashboard/company/propose-topics': typeof DashboardCompanyProposeTopicsLazyRoute
  '/dashboard/student/homepage': typeof DashboardStudentHomepageLazyRoute
  '/dashboard/student/my-projects': typeof DashboardStudentMyProjectsLazyRoute
  '/dashboard/student/propose-topic': typeof DashboardStudentProposeTopicLazyRoute
  '/dashboard/student/suggested-topics': typeof DashboardStudentSuggestedTopicsLazyRoute
  '/dashboard/teacher/archive': typeof DashboardTeacherArchiveLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/defense-selction': typeof DashboardTeacherDefenseSelctionLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/my-supervised-projects': typeof DashboardTeacherMySupervisedProjectsLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthLazyRouteWithChildren
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/owner': typeof OwnerLazyRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/one-time-password': typeof AuthOneTimePasswordLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/dashboard/admin': typeof DashboardAdminLazyRouteWithChildren
  '/dashboard/company': typeof DashboardCompanyLazyRouteWithChildren
  '/dashboard/student': typeof DashboardStudentLazyRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherLazyRouteWithChildren
  '/owner/owner': typeof OwnerOwnerLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/admin/add-user': typeof DashboardAdminAddUserLazyRoute
  '/dashboard/admin/archive': typeof DashboardAdminArchiveLazyRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardLazyRoute
  '/dashboard/admin/defense-schedule': typeof DashboardAdminDefenseScheduleLazyRoute
  '/dashboard/admin/email-schedule': typeof DashboardAdminEmailScheduleLazyRoute
  '/dashboard/admin/email-template': typeof DashboardAdminEmailTemplateLazyRoute
  '/dashboard/admin/pfe-proposals': typeof DashboardAdminPfeProposalsLazyRoute
  '/dashboard/admin/project-managment': typeof DashboardAdminProjectManagmentLazyRoute
  '/dashboard/admin/rooms': typeof DashboardAdminRoomsLazyRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionLazyRoute
  '/dashboard/admin/user-management': typeof DashboardAdminUserManagementLazyRoute
  '/dashboard/company/homepage': typeof DashboardCompanyHomepageLazyRoute
  '/dashboard/company/my-projects': typeof DashboardCompanyMyProjectsLazyRoute
  '/dashboard/company/propose-topics': typeof DashboardCompanyProposeTopicsLazyRoute
  '/dashboard/student/homepage': typeof DashboardStudentHomepageLazyRoute
  '/dashboard/student/my-projects': typeof DashboardStudentMyProjectsLazyRoute
  '/dashboard/student/propose-topic': typeof DashboardStudentProposeTopicLazyRoute
  '/dashboard/student/suggested-topics': typeof DashboardStudentSuggestedTopicsLazyRoute
  '/dashboard/teacher/archive': typeof DashboardTeacherArchiveLazyRoute
  '/dashboard/teacher/dashboard': typeof DashboardTeacherDashboardLazyRoute
  '/dashboard/teacher/defense-selction': typeof DashboardTeacherDefenseSelctionLazyRoute
  '/dashboard/teacher/manage-defense-schedule': typeof DashboardTeacherManageDefenseScheduleLazyRoute
  '/dashboard/teacher/my-supervised-projects': typeof DashboardTeacherMySupervisedProjectsLazyRoute
  '/dashboard/teacher/pending-revisions': typeof DashboardTeacherPendingRevisionsLazyRoute
  '/dashboard/teacher/submit-proposal': typeof DashboardTeacherSubmitProposalLazyRoute
  '/dashboard/teacher/supervise-projects': typeof DashboardTeacherSuperviseProjectsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/owner'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/owner/owner'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/archive'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-management'
    | '/dashboard/company/homepage'
    | '/dashboard/company/my-projects'
    | '/dashboard/company/propose-topics'
    | '/dashboard/student/homepage'
    | '/dashboard/student/my-projects'
    | '/dashboard/student/propose-topic'
    | '/dashboard/student/suggested-topics'
    | '/dashboard/teacher/archive'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/defense-selction'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/my-supervised-projects'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/owner'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/owner/owner'
    | '/dashboard'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/archive'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-management'
    | '/dashboard/company/homepage'
    | '/dashboard/company/my-projects'
    | '/dashboard/company/propose-topics'
    | '/dashboard/student/homepage'
    | '/dashboard/student/my-projects'
    | '/dashboard/student/propose-topic'
    | '/dashboard/student/suggested-topics'
    | '/dashboard/teacher/archive'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/defense-selction'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/my-supervised-projects'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/owner'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/one-time-password'
    | '/auth/reset-password'
    | '/dashboard/admin'
    | '/dashboard/company'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/owner/owner'
    | '/dashboard/'
    | '/dashboard/admin/add-user'
    | '/dashboard/admin/archive'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/defense-schedule'
    | '/dashboard/admin/email-schedule'
    | '/dashboard/admin/email-template'
    | '/dashboard/admin/pfe-proposals'
    | '/dashboard/admin/project-managment'
    | '/dashboard/admin/rooms'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/user-management'
    | '/dashboard/company/homepage'
    | '/dashboard/company/my-projects'
    | '/dashboard/company/propose-topics'
    | '/dashboard/student/homepage'
    | '/dashboard/student/my-projects'
    | '/dashboard/student/propose-topic'
    | '/dashboard/student/suggested-topics'
    | '/dashboard/teacher/archive'
    | '/dashboard/teacher/dashboard'
    | '/dashboard/teacher/defense-selction'
    | '/dashboard/teacher/manage-defense-schedule'
    | '/dashboard/teacher/my-supervised-projects'
    | '/dashboard/teacher/pending-revisions'
    | '/dashboard/teacher/submit-proposal'
    | '/dashboard/teacher/supervise-projects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthLazyRoute: typeof AuthLazyRouteWithChildren
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  OwnerLazyRoute: typeof OwnerLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthLazyRoute: AuthLazyRouteWithChildren,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  OwnerLazyRoute: OwnerLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/owner"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth": {
      "filePath": "auth.lazy.tsx",
      "children": [
        "/auth/forget-password",
        "/auth/login",
        "/auth/one-time-password",
        "/auth/reset-password"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx",
      "children": [
        "/dashboard/admin",
        "/dashboard/company",
        "/dashboard/student",
        "/dashboard/teacher",
        "/dashboard/"
      ]
    },
    "/owner": {
      "filePath": "owner.lazy.tsx",
      "children": [
        "/owner/owner"
      ]
    },
    "/auth/forget-password": {
      "filePath": "auth/forget-password.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/one-time-password": {
      "filePath": "auth/one-time-password.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.lazy.tsx",
      "parent": "/auth"
    },
    "/dashboard/admin": {
      "filePath": "dashboard/admin.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/admin/add-user",
        "/dashboard/admin/archive",
        "/dashboard/admin/dashboard",
        "/dashboard/admin/defense-schedule",
        "/dashboard/admin/email-schedule",
        "/dashboard/admin/email-template",
        "/dashboard/admin/pfe-proposals",
        "/dashboard/admin/project-managment",
        "/dashboard/admin/rooms",
        "/dashboard/admin/supervision",
        "/dashboard/admin/user-management"
      ]
    },
    "/dashboard/company": {
      "filePath": "dashboard/company.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/company/homepage",
        "/dashboard/company/my-projects",
        "/dashboard/company/propose-topics"
      ]
    },
    "/dashboard/student": {
      "filePath": "dashboard/student.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/student/homepage",
        "/dashboard/student/my-projects",
        "/dashboard/student/propose-topic",
        "/dashboard/student/suggested-topics"
      ]
    },
    "/dashboard/teacher": {
      "filePath": "dashboard/teacher.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/teacher/archive",
        "/dashboard/teacher/dashboard",
        "/dashboard/teacher/defense-selction",
        "/dashboard/teacher/manage-defense-schedule",
        "/dashboard/teacher/my-supervised-projects",
        "/dashboard/teacher/pending-revisions",
        "/dashboard/teacher/submit-proposal",
        "/dashboard/teacher/supervise-projects"
      ]
    },
    "/owner/owner": {
      "filePath": "owner/owner.lazy.tsx",
      "parent": "/owner"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/admin/add-user": {
      "filePath": "dashboard/admin/add-user.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/archive": {
      "filePath": "dashboard/admin/archive.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/dashboard": {
      "filePath": "dashboard/admin/dashboard.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/defense-schedule": {
      "filePath": "dashboard/admin/defense-schedule.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/email-schedule": {
      "filePath": "dashboard/admin/email-schedule.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/email-template": {
      "filePath": "dashboard/admin/email-template.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/pfe-proposals": {
      "filePath": "dashboard/admin/pfe-proposals.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/project-managment": {
      "filePath": "dashboard/admin/project-managment.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/rooms": {
      "filePath": "dashboard/admin/rooms.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/supervision": {
      "filePath": "dashboard/admin/supervision.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/admin/user-management": {
      "filePath": "dashboard/admin/user-management.lazy.tsx",
      "parent": "/dashboard/admin"
    },
    "/dashboard/company/homepage": {
      "filePath": "dashboard/company/homepage.lazy.tsx",
      "parent": "/dashboard/company"
    },
    "/dashboard/company/my-projects": {
      "filePath": "dashboard/company/my-projects.lazy.tsx",
      "parent": "/dashboard/company"
    },
    "/dashboard/company/propose-topics": {
      "filePath": "dashboard/company/propose-topics.lazy.tsx",
      "parent": "/dashboard/company"
    },
    "/dashboard/student/homepage": {
      "filePath": "dashboard/student/homepage.lazy.tsx",
      "parent": "/dashboard/student"
    },
    "/dashboard/student/my-projects": {
      "filePath": "dashboard/student/my-projects.lazy.tsx",
      "parent": "/dashboard/student"
    },
    "/dashboard/student/propose-topic": {
      "filePath": "dashboard/student/propose-topic.lazy.tsx",
      "parent": "/dashboard/student"
    },
    "/dashboard/student/suggested-topics": {
      "filePath": "dashboard/student/suggested-topics.lazy.tsx",
      "parent": "/dashboard/student"
    },
    "/dashboard/teacher/archive": {
      "filePath": "dashboard/teacher/archive.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/dashboard": {
      "filePath": "dashboard/teacher/dashboard.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/defense-selction": {
      "filePath": "dashboard/teacher/defense-selction.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/manage-defense-schedule": {
      "filePath": "dashboard/teacher/manage-defense-schedule.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/my-supervised-projects": {
      "filePath": "dashboard/teacher/my-supervised-projects.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/pending-revisions": {
      "filePath": "dashboard/teacher/pending-revisions.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/submit-proposal": {
      "filePath": "dashboard/teacher/submit-proposal.lazy.tsx",
      "parent": "/dashboard/teacher"
    },
    "/dashboard/teacher/supervise-projects": {
      "filePath": "dashboard/teacher/supervise-projects.lazy.tsx",
      "parent": "/dashboard/teacher"
    }
  }
}
ROUTE_MANIFEST_END */
